# Generated by Django 6.1 on 2026-08-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='body_part',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='level',
            field=models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20),
        ),
    ]
